### ISSUE TITLE
GPU显存需求

### ISSUE THREAD

**Issue by whisney** [chaoyi-wu/RadFM#1]
你好！我看论文中提到使用的NVIDIA A100 GPU（80GB）训练模型，每一个GPU上batchsiz为1，请问如果我希望使用自己的3D数据微调所提出的预训练的3D ViT，具体需要多少显存？所需要的显存是不是应该与输入图像的尺寸相关？
我看论文提到的数据预处理是将输入的3D图像最大限制在了（64，256，256）的大小，如果就是（64，256，256）这个尺寸作为输入，需要占用多少显存？

**Comment by chaoyi-wu** [comment]
如果只是vision encoder的话现存要求不大，但具体需要多大我不太清楚，确实是和输入图片大小有关。



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月07日 12:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [chaoyi-wu/RadFM] GPU显存需求 (Issue #1) |

你好！我看论文中提到使用的NVIDIA A100 GPU（80GB）训练模型，每一个GPU上batchsiz为1，请问如果我希望使用自己的3D数据微调所提出的预训练的3D ViT，具体需要多少显存？所需要的显存是不是应该与输入图像的尺寸相关？
我看论文提到的数据预处理是将输入的3D图像最大限制在了（64，256，256）的大小，如果就是（64，256，256）这个尺寸作为输入，需要占用多少显存？

**Comment by whisney** [comment]
> 如果只是vision encoder的话显存要求不大，但具体需要多大我不太清楚，我们训练的时候都是带着LLM一起的，确实是和输入图片大小有关。

请问Model checkpoint中哪个文件保存的是vision encoder的权重？

**Comment by chaoyi-wu** [comment]
权重是整个model的，暂时没有单独的分包，我们之后会考虑分part上传

**Comment by whisney** [comment]
请问MyEmbedding函数中的"/gpfs/home/cs/leijiayu/wuchaoyi/multi_modal/src/MedKEBERT"在哪里下载？

**Comment by chaoyi-wu** [comment]
https://huggingface.co/xmcmic/Med-KEBERT/tree/main 这个repo，代码中已经修改为了huggingface pull model
