### ISSUE TITLE
change prompt

### ISSUE THREAD

**Issue by zzzzxciid** [chaoyi-wu/RadFM#10]
The work you've done is truly commendable and holds immense potential.

However, I've come across an issue that I'd like to bring to your attention. When using specific queries, particularly those related to medical imaging such as "Please write a report for this X-ray image" or "Please write a radiology report consists of findings that explains this medical scan", the model either provides no response or consistently outputs "MS Plaques".

So what prompt should I use to let this have outputs?

**Comment by chaoyi-wu** [comment]
Sorry, there is a bug in quick demo and I have fixed it. 

You may try it again and ensure punctuation is complete. However, the current model is sensitive to prompts and if you hope it to answer the question following the report format, you may better check ```src/Dataset/dataset/report_prompt.json``` and pick a prompt template for writing reports.

**Comment by zzzzxciid** [comment]
It works! Thank you!
