### ISSUE TITLE
Is there a requirement for input text for the model?

### ISSUE THREAD

**Issue by Tyangn** [chaoyi-wu/RadFM#15]
Hello!
I rewrite the question in Quick_demo test.py such as "Please write a report for this scan". but it outputs nothing. So I want to know if there has a requirement for input text?

**Comment by chaoyi-wu** [comment]
Please check this [issue](https://github.com/chaoyi-wu/RadFM/issues/10). First you need to write a dot at the end, compared with the trillion-level LLMs, our small-scale model actually is sensitive to prompts what is also we hope to improve in the future.  For report writing, I better recommend you to follow the [issue](https://github.com/chaoyi-wu/RadFM/issues/10) to use our seen instructions, the model will perform better.

**Comment by Tyangn** [comment]
It works, thank you. Your work is really awesome.
