### ISSUE TITLE
Rad3d data not complete

### ISSUE THREAD

**Issue by JINGEWU** [chaoyi-wu/RadFM#20]
Hello, I downloaded the radiopaedia data you provided and found that the rad3d_train.json seems not valid. It shows "Unterminated string starting at: line 1704502 column 13 (char 80168752)" when loading it in python. And I checked the json file, it seems to be incomplete after line 1704502. Could you double check and share the full version with us? Thank you very much!

**Comment by chaoyi-wu** [comment]
Thanks for the issue and it has been updated.
