### ISSUE TITLE
Rad3D Dataset

### ISSUE THREAD

**Issue by tang-bd** [chaoyi-wu/RadFM#24]
Hello, I downloaded the radiopaedia data you updated recently and found that the rad3d_train.json seems to be incomplete after line 764425. Could you double check and share the full version with us? Additionally, It seems that all image files whose "image_path" in the json files that have ".npy" as the postfix of their values cannot be found. Can you fix this as well?
Thank you for your great contribution to the community.

**Comment by tang-bd** [comment]
Another problem is that the "image_path" in many of your csv files related to the Rad3D Dataset seems not correct as well. They are all in the format "processed_images/0/N.npy" where N is some integer, which does not match the directory structure we got after processing the images. I guess the "radio_modality_test/train.csv" files are the only correct ones.

**Comment by chaoyi-wu** [comment]
https://github.com/chaoyi-wu/RadFM/blob/main/src/Dataset/dataset/nii2npy_for_radiopaedio.py. Sorry for missing. We have uploaded the file here. For a certain npy file, we stack all nii scans together to accelerate the dataloader.

**Comment by tang-bd** [comment]
Thank you for your efforts. Can you fix rad3d_train.json as well?

**Comment by zihui-debug** [comment]
> Hello, I downloaded the radiopaedia data you updated recently and found that the rad3d_train.json seems to be incomplete after line 764425. Could you double check and share the full version with us? Additionally, It seems that all image files whose "image_path" in the json files that have ".npy" as the postfix of their values cannot be found. Can you fix this as well? Thank you for your great contribution to the community.

Hello, where did you download the 3d image data?

**Comment by tang-bd** [comment]
> > Hello, I downloaded the radiopaedia data you updated recently and found that the rad3d_train.json seems to be incomplete after line 764425. Could you double check and share the full version with us? Additionally, It seems that all image files whose "image_path" in the json files that have ".npy" as the postfix of their values cannot be found. Can you fix this as well? Thank you for your great contribution to the community.
> 
> Hello, where did you download the 3d image data?

It seems that the authors have closed the access to the 3d image data and I downloaded the data before that.

**Comment by chaoyi-wu** [comment]
> > Hello, I downloaded the radiopaedia data you updated recently and found that the rad3d_train.json seems to be incomplete after line 764425. Could you double check and share the full version with us? Additionally, It seems that all image files whose "image_path" in the json files that have ".npy" as the postfix of their values cannot be found. Can you fix this as well? Thank you for your great contribution to the community.
> 
> Hello, where did you download the 3d image data?

Yes. We have withdrawn the download link due to license. You can mail the radiopaedio for permission and cc for us. Then we are quite willing for sharing you the download link again.
