### ISSUE TITLE
Image Format Inconsistency between the Codes and the Downloaded Disease Diagnosis Datasets

### ISSUE THREAD

**Issue by jianghao-zhang** [chaoyi-wu/RadFM#25]
Hi, thanks for sharing such a meaningful work!

I encountered an issue while testing the downloaded disease diagnosis datasets (e.g., Vindr-SpineXR, Vindr-PCXR, and Vindr-Mammo). The image formats in these datasets are ".dicom", whereas the .csv file you uploaded in Hugging Face uses the ".png" format. I have attached a screenshot to illustrate this issue:

<img width="1162" alt="image" src="https://github.com/chaoyi-wu/RadFM/assets/81921082/91026b06-fd45-4e46-976e-9724d4ccec8e">

Given this situation, I kindly request your assistance in providing a straightforward guide or instructions on converting the ".dicom" files to ".png" format. This guidance would be immensely beneficial not only to me but potentially to other users who might encounter the same challenge.

**Comment by manuel-tran** [comment]
I have the same question, my dataset consists of ".dicom" images. What is the step-by-step process to convert them to ".png" format? This is crucial to get the same input distribution.

**Comment by chaoyi-wu** [comment]
Thanks  for your reminder. Sorry for missing this file we have added the converting python ode in https://github.com/chaoyi-wu/RadFM/blob/main/src/Dataset/dataset/dicom_to_png_for_VinDR_sampled_using_mammo.py. The file is about Vindr-mammo and for other dataset the code is mostly the same. Hope this can help you.

**Comment by jianghao-zhang** [comment]
> Thanks for your reminder. Sorry for missing this file. We have added the converting python code in https://github.com/chaoyi-wu/RadFM/blob/main/src/Dataset/dataset/dicom_to_png_for_VinDR_sampled_using_mammo.py. The file is about Vindr-mammo and for other dataset the code is mostly the same. Hope this can help you.

Thanks for your efforts!
