### ISSUE TITLE
Report generation results are poor when use quick demo test

### ISSUE THREAD

**Issue by warmbreeze92** [chaoyi-wu/RadFM#38]
Q1：When I test in the quick demo to generate a report using the same prompt as in the article, like “Please generate a radiology report for this scan <image-1>”, the results are always short phrases such as “Left sided atelectasis” instead of a long paragraph report. What‘s the reason for this?  
Q2: there is no output when the end of the input prompt does not include punctuation

**Comment by RobsoUganda** [comment]
He did respond to it here Issue[10](https://github.com/chaoyi-wu/RadFM/issues/10)

**Comment by babbu3682** [comment]
Despite using the same report genistration prompt, it shows pore results. Did you solve it?

**Comment by dt-yuhui** [comment]
Same question
