### ISSUE TITLE
这模型怎么解压？

### ISSUE THREAD

**Issue by shuxiaobo** [chaoyi-wu/RadFM#4]
这模型怎么解压？

**Comment by chaoyi-wu** [comment]
https://pan.baidu.com/s/1A-K5nXCbvWAVqvb6dLjYJg?pwd=q1eo 我把原始文件传输到百度网盘了

**Comment by chaoyi-wu** [comment]
也可以参考这个做解压 https://blog.csdn.net/qq_39779233/article/details/127408291
