### ISSUE TITLE
Rad3D dataset

### ISSUE THREAD

**Issue by maximek3** [chaoyi-wu/RadFM#8]
Hi, are there any plans to release the Rad3D dataset?

**Comment by JonghwanMun** [comment]
+1

In addition, I wonder if there is a plan to release MPx-series.

**Comment by chaoyi-wu** [comment]
Uploading and after finishing, I will update the github

**Comment by JLrumberger** [comment]
Any updates on this? I'd be super happy to get my hands on the dataset.
